// Fetch the two pixel typefaces and inline them into css/fonts.css as data
// URIs. Embedding rather than linking is deliberate: a CDN link would break
// offline play, and the Artifact CSP blocks external font hosts outright.
//
// Both faces are SIL Open Font License 1.1.
//
// Usage: node tools/make_fonts.mjs

import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36';

const FACES = [
  { family: 'Silkscreen', weight: 400, css: 'Silkscreen' },
  { family: 'Silkscreen', weight: 700, css: 'Silkscreen:wght@700' },
  { family: 'Pixelify Sans', weight: 400, css: 'Pixelify+Sans' },
  { family: 'Pixelify Sans', weight: 700, css: 'Pixelify+Sans:wght@700' },
];

/** Google serves one @font-face per unicode subset; we only ship latin. */
function latinUrl(css) {
  const blocks = css.split('@font-face').slice(1);
  const latin = blocks.find((b) => /\/\*\s*latin\s*\*\//.test(css.slice(0, css.indexOf(b))))
    ?? blocks[blocks.length - 1];
  return latin.match(/src:\s*url\(([^)]+)\)/)?.[1];
}

async function fetchFace({ family, weight, css }) {
  const url = `https://fonts.googleapis.com/css2?family=${css}&display=swap`;
  const sheet = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();

  // Pick the block immediately preceded by the `/* latin */` comment.
  const parts = sheet.split('/*');
  const latinPart = parts.find((p) => p.trimStart().startsWith('latin */'));
  const src = latinPart?.match(/src:\s*url\(([^)]+)\)/)?.[1] ?? latinUrl(sheet);
  if (!src) throw new Error(`no latin subset for ${family} ${weight}`);

  const buf = Buffer.from(await (await fetch(src, { headers: { 'User-Agent': UA } })).arrayBuffer());
  console.log(`${family} ${weight}: ${(buf.length / 1024).toFixed(1)} KB`);
  return { family, weight, b64: buf.toString('base64') };
}

const faces = [];
for (const f of FACES) faces.push(await fetchFace(f));

const css = `/* Generated by tools/make_fonts.mjs — do not edit by hand.
 *
 * Silkscreen and Pixelify Sans, both SIL Open Font License 1.1.
 *   Silkscreen    (c) Jason Kottke        https://fonts.google.com/specimen/Silkscreen
 *   Pixelify Sans (c) Stefie Justprince   https://fonts.google.com/specimen/Pixelify+Sans
 *
 * Inlined as data URIs so the game keeps its typography offline and inside a
 * strict content-security policy.
 */

${faces.map((f) => `@font-face {
  font-family: '${f.family}';
  font-style: normal;
  font-weight: ${f.weight};
  font-display: block;
  src: url(data:font/woff2;base64,${f.b64}) format('woff2');
}`).join('\n\n')}
`;

writeFileSync(resolve(ROOT, 'css/fonts.css'), css);
console.log(`\ncss/fonts.css  ${(css.length / 1024).toFixed(0)} KB`);
